apiVersion: v1
kind: Namespace
metadata:
  name: prd
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: echo-ip-freestyle
  name: echo-ip-freestyle
  namespace: prd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: echo-ip-freestyle
  template:
    metadata:
      labels:
        app: echo-ip-freestyle
    spec:
      containers:
      - image: 192.168.1.10:8443/echo-ip:latest
        name: echo-ip
