jenkins:
  clouds:
  - kubernetes:
      name: "kubernetes"
      namespace: "default"
      podLabels:
      - key: "jenkins/jenkins-jenkins-slave"
        value: "true"
      serverUrl: "https://kubernetes.default"
      templates:
      - containers:
        - args: "^${computer.jnlpmac} ^${computer.name}"
          command: ""
          envVars:
          - envVar:
              key: "JENKINS_URL"
              value: "http://192.168.1.11"
          image: "jenkins/inbound-agent:4.3-4"
          name: "jnlp"
        label: "jenkins-jenkins-slave "
        name: "default"
        runAsGroup: "993"
        runAsUser: "1000"
        serviceAccount: "jenkins"
        volumes:
        - hostPathVolume:
            hostPath: "/usr/bin/kubectl"
            mountPath: "/usr/bin/kubectl"
        - hostPathVolume:
            hostPath: "/bin/docker"
            mountPath: "/bin/docker"
        - hostPathVolume:
            hostPath: "/var/run/docker.sock"
            mountPath: "/var/run/docker.sock"
  crumbIssuer:
    standard:
      excludeClientIPFromCrumb: true
